// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQXK_8MWpwVP1kOAt0ruIU2QE-39udoxg',
    appId: '1:974077398990:web:50cab74662f4eaa87ce59f',
    messagingSenderId: '974077398990',
    projectId: 'project-40c46',
    authDomain: 'project-40c46.firebaseapp.com',
    storageBucket: 'project-40c46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAupBv-BAIYimOLWRWUzIQF1JOKt2HK6a0',
    appId: '1:974077398990:android:29bab83df811fddc7ce59f',
    messagingSenderId: '974077398990',
    projectId: 'project-40c46',
    storageBucket: 'project-40c46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqqCgcFfuptD23yK4bcF1uP_bs6XALijg',
    appId: '1:974077398990:ios:103bea08e03ccaf27ce59f',
    messagingSenderId: '974077398990',
    projectId: 'project-40c46',
    storageBucket: 'project-40c46.appspot.com',
    iosClientId: '974077398990-ct9ik6lft97aq0qd6m3fd58rfgu6nq92.apps.googleusercontent.com',
    iosBundleId: 'com.example.mark4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqqCgcFfuptD23yK4bcF1uP_bs6XALijg',
    appId: '1:974077398990:ios:e3562d0929e757617ce59f',
    messagingSenderId: '974077398990',
    projectId: 'project-40c46',
    storageBucket: 'project-40c46.appspot.com',
    iosClientId: '974077398990-fhthvept20b28cg7hlrj0f1rs8rggt2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mark4.RunnerTests',
  );
}
