name: mart3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  # cached_network_image: ^3.1.0+1
  # collection: ^1.15.0
  # flutter_animate: ^4.1.1+1
  # flutter_cache_manager: ^3.3.0
  # font_awesome_flutter: ^10.1.0
  # from_css_color: ^2.0.0
  go_router: ^12.1.3
  google_fonts: ^2.2.0
  intl: ^0.17.0
  json_path: ^0.3.1
  # page_transition: ^2.0.4
  path_provider: ^2.0.14
  path_provider_android: ^2.0.25
  path_provider_foundation: ^2.2.2
  # path_provider_platform_interface: ^2.0.6
  provider: ^5.0.0
  shared_preferences: ^2.0.11
  shared_preferences_android: ^2.2.1
  shared_preferences_foundation: ^2.3.4
  shared_preferences_platform_interface: ^2.3.1
  shared_preferences_web: ^2.2.1
  sqflite: ^2.2.6
  timeago: ^3.1.0
  url_launcher: ^6.0.15
  url_launcher_android: ^6.3.0
  url_launcher_ios: ^6.2.5
  url_launcher_platform_interface: ^2.3.2
  flutterflow: ^0.1.1
  flutterflow_ui: ^0.2.0

dependency_overrides:
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: Readex Pro
      fonts:
        - asset: fonts/ReadexPro-Regular.ttf
        - asset: fonts/ReadexPro-Bold.ttf
          weight: 700
